version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:
